### ISSUE TITLE
v2.2.0 breaking Jest tests

### ISSUE THREAD

**Issue by dermyhughes** [wojtekmaj/get-user-locale#87]
Hi,

We have components that have `get-user-locale` as a dependency. As of `v2.2.0`, our Jest tests are failing due to a `SyntaxError: Cannot use import statement outside a module` error. Rolling back to `v2.1.3` fixes the issue.

We have followed the Jest docs mentioned in the error to resolve but have been unable to fix.

Full error example below:

```
FAIL  packages/filter-date-picker/tests/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/dermot.hughes/Documents/git/aperture-components/packages/date-picker/node_modules/get-user-locale/dist/esm/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import memoize from 'lodash.memoize';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       8 | var ExternalDatePicker = require('react-date-picker/dist/entry.nostyle');
       9 | var reactPositioningPortal = require('@codastic/react-positioning-portal');
    > 10 | var getUserLocale = require('get-user-locale');
         |                     ^
      11 | var dateFns = require('date-fns');
      12 | var ReactCalendar = require('react-calendar');
      13 | var ExternalDateRangePicker = require('@wojtekmaj/react-daterange-picker');

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)
      at Object.require (packages/date-picker/dist/index.js:10:21)
      at Object.require (packages/filter-date-picker/filter-date-picker.tsx:9:1)
      at Object.require (packages/filter-date-picker/index.ts:1:1)
      at Object.require (packages/filter-date-picker/tests/index.test.js:5:1)
      
```

**Comment by wojtekmaj** [comment]
Try  
```
"transformIgnorePatterns": [
    "/node_modules/(?!(get-user-locale))"
  ]
```

Jest is notoriously bad at dealing with ESM modules... In 2023.

**Comment by dermyhughes** [comment]
Thank you! I thought I had already tried this while debugging with no luck but this has solved the issue.
